version: "3.1"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.volumes/conf:/etc/nginx/conf.d
      - ./.volumes/vhost:/etc/nginx/vhost.d
      - ./.volumes/html:/usr/share/nginx/html
      - ./.volumes/dhparam:/etc/nginx/dhparam
      - ./.volumes/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always


  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx-proxy
    volumes:
      - ./.volumes/vhost:/etc/nginx/vhost.d
      - ./.volumes/html:/usr/share/nginx/html
      - ./.volumes/dhparam:/etc/nginx/dhparam
      - ./.volumes/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=seppe.lenders@gmail.com
    restart: always


  root:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=seppe.dev
      - LETSENCRYPT_HOST=seppe.dev


networks:
  default:
    name: reverse-proxy
