version: "3.1"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.volumes/conf:/etc/nginx/conf.d
      - ./.volumes/vhost:/etc/nginx/vhost.d
      - ./.volumes/html:/usr/share/nginx/html
      - ./.volumes/dhparam:/etc/nginx/dhparam
      - ./.volumes/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - internal
      - external


  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - ./.volumes/vhost:/etc/nginx/vhost.d
      - ./.volumes/html:/usr/share/nginx/html
      - ./.volumes/dhparam:/etc/nginx/dhparam
      - ./.volumes/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=seppe.lenders@gmail.com
    networks:
      - internal


  nginx:
    image: nginx
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=seppe.lenders.dev,lenders.dev,www.lenders.dev
      - LETSENCRYPT_HOST=seppe.lenders.dev,lenders.dev,www.lenders.dev
    networks:
      - internal

networks:
  internal:
  external:
